enableGlobalCache: true

yarnPath: '.yarn/releases/yarn-berry.cjs'

npmRegistryServer: 'https://registry.npm.taobao.org'

unsafeHttpWhitelist:

# nodeLinker: pnp
nodeLinker: node-modules
# pnpMode: loose

# httpProxy: 'http://127.0.0.1:7890'
# httpsProxy: 'http://127.0.0.1:7890'
