# 谷歌分析
google_analytics:
  ga_measurement_id: 'UA-146082840-1'

generator:
  per_page: 10
  order_by: '-date'
  # order: -1 # not support

menu:
  home:
    link: /
    icon: home
    name: 首页
  archives:
    link: /archives/
    icon: archive
    name: 归档
  categories:
    link: /categories/
    icon: th
    name: 分类
  about:
    link: /about/
    icon: user
    name: 关于
  tags:
    link: /resume/
    icon: tag
    name: 标签
  # schedule:
  #   icon: calendar
  # sitemap:
  #   icon: sitemap
  # commonweal:
  #   icon: heartbeat

highlight:
  # @see https://github.com/highlightjs/highlight.js/tree/master/src/styles
  theme: solarized-dark
