# 头像
avatar: '/images/avatar.jpg'

# 关闭一言
disableHitokoto: false

# 谷歌分析
google_analytics:
  ga_measurement_id: 'UA-146082840-1'

generator:
  per_page: 10
  order_by: '-date'
  # order: -1 # not support

menu:
  home:
    link: /
    icon: home
    name: 首页
  archives:
    link: /archives/
    icon: archive
    name: 归档
  categories:
    link: /categories/
    icon: category
    name: 分类
  about:
    link: /about/
    icon: person
    name: 关于
  tags:
    link: /tags/
    icon: tag
    name: 标签
  # schedule:
  #   icon: calendar
  # sitemap:
  #   icon: sitemap
  # commonweal:
  #   icon: heartbeat

highlight:
  # @see https://github.com/highlightjs/highlight.js/tree/master/src/styles
  theme: solarized-dark

# 社交
social:
  enable: true
  GitHub:
    link: https://github.com/daief
    icon: github
    name: GitHub
  WeChat:
    link: /images/wechat.jpg
    icon: wechat
    name: WeChat
  Email:
    link: mailto:defeng_mail@163.com
    icon: email
    name: Email
  #Weibo: https://github.com/daief
