# 谷歌分析
google_analytics:
  ga_measurement_id: 'UA-146082840-1'

generator:
  per_page: 10
  order_by: '-date'
  # order: -1 # not support

menu:
  home:
    link: /
    icon: home
  archives:
    link: /archives/
    icon: archive
  categories:
    link: /categories/
    icon: th
  about:
    link: /about/
    icon: user
  tags:
    link: /tags/
    icon: tag
  # schedule:
  #   icon: calendar
  # sitemap:
  #   icon: sitemap
  # commonweal:
  #   icon: heartbeat
